M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date lun 28 sep 2026 21:43:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T21:43:13-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.000
%
G90
G05
T1
X113.719Y-146.375
X149.219Y-146.375
T2
X158.4Y-132.75
M30
