M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date jue 15 ago 2024 22:22:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-15T22:22:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X101.5Y-104.0
X141.5Y-104.0
T0
M30
