M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date jue 15 ago 2024 22:54:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-15T22:54:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
%
G90
G05
T1
X101.5Y-106.7
X141.5Y-101.3
T0
M30
