M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu20.04.1} date lun 05 ago 2024 23:26:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-05T23:26:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X23.0Y-132.0
X199.0Y-38.0
T0
M30
